---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: bosh-src
- name: golang-release
- name: stemcell

run:
  path: golang-release/ci/tasks/test.sh

params:
  PRIVATE_YML: replace-me
