---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: bosh-src
- name: golang-release
- name: stemcell

run:
  path: bosh-src/ci/tasks/test.sh
