---
name: test

releases:
- name: golang
  version: create
  url: file://.

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: golang-1.8-test
  azs: [z1]
  instances: 1
  jobs:
  - name: golang-1.8-test
    release: golang
    properties: {}
  vm_type: default
  stemcell: default
  networks:
  - name: default
