---
groups:
- name: golang-release
  jobs:
  - test
  - bump

jobs:
- name: test
  serial: true
  plan:
  - aggregate:
    - get: golang-release
    - get: bosh-src
    - get: stemcell
  - task: test
    privileged: true
    file: golang-release/ci/tasks/test.yml

- name: bump
  serial: true
  plan:
  - aggregate:
    - get: golang
      trigger: true
    - get: golang-release
    - get: bosh-src
    - get: stemcell
  - task: bump
    file: golang-release/ci/tasks/bump.yml

resources:
- name: bosh-src
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh.git
    branch: master

- name: golang-release
  type: git
  source:
    uri: https://github.com/bosh-packages/golang-release.git
    branch: master

- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent

- name: golang
  type: dynamic-metalink
  source:
    version_check: |
      curl -s https://golang.org/dl/?mode=json | jq -r '.[].version[2:]'
    metalink_get: |
      curl -s https://golang.org/dl/?mode=json | jq '
        map(select(.version[2:] == env.version)) | map({
          "files": (.files | map({
            "name": .filename,
            "size": .size,
            "urls": [ { "url": "https://dl.google.com/go/\(.filename)" } ],
            "hashes": [ { "type": "sha-256", "hash": .sha256 } ] } ) ) } )[]'
    version: 1.9.x
    include_files:
    - go*.linux-amd64.tar.gz

resource_types:
- name: dynamic-metalink
  type: docker-image
  source:
    repository: dpb587/dynamic-metalink-resource<Paste>
